apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-app-01
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chezmoi-sh/argocd-extension-application-map.git
    targetRevision: main
    path: examples/applications-maze/argocd-example-apps/guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook-app-01
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
