apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-a
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chezmoi-sh/argocd-extension-application-map.git
    targetRevision: main
    path: examples/applications-loop/application-B
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
