arrowParens: always
bracketSameLine: false
bracketSpacing: true
endOfLine: lf
jsxBracketSameLine: false
printWidth: 120
semi: true
singleQuote: true
tabWidth: 2
trailingComma: es5
useTabs: false

plugins:
  - '@trivago/prettier-plugin-sort-imports'

# @trivago/prettier-plugin-sort-imports configuration
importOrder:
  - '^@storybook/(.*)$'
  - react
  - '^@xyflow/(.*)$'
  - '^[./]'
importOrderGroupNamespaceSpecifiers: true
importOrderSeparation: true
importOrderSortSpecifiers: true
