apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-03
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: guestbook-app-04
            path: examples/applications-maze/argocd-example-apps/guestbook
            namespace: guestbook-app-04
  template:
    metadata:
      name: "{{name}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/chezmoi-sh/argocd-extension-application-map.git
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
