---
name: 🚨 Lint Everything

on:
  merge_group: {}
  pull_request: {}

concurrency:
  group: ${{ github.action }}-${{ github.event.pull_request.id }}
  cancel-in-progress: true

permissions: {}

jobs:
  trunk:
    name: ✅ Validate code quality
    permissions:
      contents: read
      checks: write
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: ⚡️ Run `trunk check`
        uses: trunk-io/trunk-action@06c428bf05832198443baab1096754b166a6c466 # v1.2.2
